### ISSUE TITLE
請問如何啟用NTVDM/OTVDM支持

### ISSUE THREAD

**Issue by neko0xff** [WhatTheBlock/WindowsSimplify#100]
不好意思大佬，能請益一下我在原裝的系統上可透過OTVDM來執行16位元的程式，但到了使用該精簡版的系統時則無法正常運行。。。

**Comment by WhatTheBlock** [comment]
因為這個組件我移除了，用到這個功能的人都是有特殊需求的，自然不會留在精簡系統中
