### ISSUE TITLE
請問要如何恢復 Windows 10 為預設的桌面圖示，而非 Windows 11 的？

### ISSUE THREAD

**Issue by jsdryan** [WhatTheBlock/WindowsSimplify#102]
您好，如主旨。

**Comment by jsdryan** [comment]
您好，有人在嗎？

**Comment by WhatTheBlock** [comment]
將原版映像的imageres.dll、shell32.dll、imagesp1.dll、mydocs.dll、zipfldr.dll覆蓋至系統裡
檔案路徑：C:\Windows\System32

**Comment by jsdryan** [comment]
> 將原版映像的imageres.dll、shell32.dll、imagesp1.dll、mydocs.dll、zipfldr.dll覆蓋至系統裡 檔案路徑：C:\Windows\System32

您好，已在安全模式下覆蓋，重新開機後還是一樣 Windows 11 的圖示，還有其他的步驟嗎？謝謝。
