### ISSUE TITLE
wusa.exe media feature pack問題

### ISSUE THREAD

**Issue by usernoobguy** [WhatTheBlock/WindowsSimplify#107]
我是小白一枚，但我鼓足勇氣提出這個問題想請教
首先我的電腦是2117u，我安裝過您提供的許多版本最後1607是最順的，並使用了很久時間
我也知道這個版本是精簡也是針對老電腦的，但我目前手邊只有這台電腦可以使用
近期我想使用phone的altstore但必須安裝itunes跟icloud，其中icloud必須有media feture pack這個東西
控制台內看這個功能不存在
我自己google了也手動下載了安裝包，但是msu格式的檔案無法開啟
我試著用英文跟中文搜尋msu installer或install tool，但始終只能透過cmd指令安裝
於是遇到圖中的情況
![擷取](https://github.com/WhatTheBlock/WindowsSimplify/assets/99551629/5baa1bd8-9068-4c8e-9c2d-ce1338f97d5f)
我想知道問題出在哪
並懇求有解決方法能使我不必重安裝系統，我已經有許多重要的資料跟軟體在內了
萬分感謝

**Comment by WhatTheBlock** [comment]
這系統移除了WinSxS，基本上所有系統更新都無法安裝

icloud你是使用exe安裝檔被提示需要media feature pack嗎?

**Comment by usernoobguy** [comment]
> 這系統移除了WinSxS，基本上所有系統更新都無法安裝
> 
> icloud你是使用exe安裝檔被提示需要media feature pack嗎?

是的，謝謝您的回答
在安裝時它就顯示要media feature pack才能繼續完成

**Comment by WhatTheBlock** [comment]
那可能沒辦法了，這個系統刪減非常多東西，所以相容性沒辦法兼顧
