### ISSUE TITLE
DIY documentation

### ISSUE THREAD

**Issue by couleurm** [WhatTheBlock/WindowsSimplify#109]
Tutorial to make your own simplify iso from default windows iso release?

**Comment by WhatTheBlock** [comment]
Maybe, I've thought about it.

**Comment by WhatTheBlock** [comment]
I have uploaded a tutorial video. For language issues, please ask others to help translate.

[https://www.youtube.com/watch?v=Rly7AVPOncQ](https://www.youtube.com/watch?v=Rly7AVPOncQ)
