### ISSUE TITLE
How to upgrade to another WindowsSimplify version

### ISSUE THREAD

**Issue by ifloppy** [WhatTheBlock/WindowsSimplify#110]
你好，请教一下。

我的主力电脑上安装了一个本项目的Windows系统。我之后是否有能够使用什么方式从现在使用的系统升级到本项目的、版本更新的Windows系统？（保留原先安装的软件等数据）

期待您的解惑。谢谢！

**Comment by WhatTheBlock** [comment]
沒辦法完全保留，系統安裝分區一定會被格式化
只能盡量將非強制安裝路徑的software安裝在非系統分區

**Comment by ifloppy** [comment]
好的，感谢解答
