### ISSUE TITLE
在虚拟机中无法使用相机

### ISSUE THREAD

**Issue by ZeekoZhu** [WhatTheBlock/WindowsSimplify#20]
用 vmware player 运行 win10 稳定版 v1，可以检测到相机，但是无法使用。

![image](https://user-images.githubusercontent.com/13861843/145664931-950a1065-cd02-47a4-9031-f84544da5039.png)

使用同样的虚拟机配置运行官方的 win10 镜像，相机设备工作正常。

**Comment by WhatTheBlock** [comment]
抱歉，這項暫時沒辦法測試，因為我電腦沒有鏡頭

**Comment by win98se** [comment]
请先检查设置应用中是否阻止了相机和摄像头访问。

**Comment by WhatTheBlock** [comment]
你好，穩定版已發布了很多新版本，再麻煩試試看，
我先關閉此issue，如還是有問題再開啟即可。
