### ISSUE TITLE
大哥能不能制作一个带wsl的精简版。只要wsl1就行。在虚拟机使用。谢谢大佬。

### ISSUE THREAD

**Issue by ChaunceyShannon** [WhatTheBlock/WindowsSimplify#24]

**Comment by WhatTheBlock** [comment]
可以提供詳細一點的要求嗎？
是否還有其他用途？
系統語言要以英文還是簡中為主？

**Comment by ChaunceyShannon** [comment]
请问可以用win11吗，win11更炫酷嘞。

**Comment by ChaunceyShannon** [comment]
而且听说win10在2025年就要淘汰了，我想如果有一个好系统，我可以用很久呢。

**Comment by WhatTheBlock** [comment]
> 请问可以用win11吗，win11更炫酷嘞。

可以

**Comment by WhatTheBlock** [comment]
> > > 请问可以用win11吗，win11更炫酷嘞。
> > 
> > 
> > 可以
> 
> 谢谢大佬。还有个卑微的请求，精简的时候小心不要把Unity模式的支援模组也去掉了哈。不过，我也不知道到底是哪个模组支援了Unity模式。哈哈

了解，我到時候再一併測試

**Comment by ChaunceyShannon** [comment]
> 那我以英文的win10來製作 以你的需求應該是要極限精簡了

我考虑了一下，极限精简，是不是会有一些问题，我有可能会需要用到office，你也知道当一个程序员的话，其实文书类工作也比较少，可是我也不知道以后会不会需要用到。

不知道是不是要求有点多哈。

机器的磁盘倒是不缺，就是内存缺，我也不知道极限精简是个什么情况，就是我觉得，例如说有一些功能，吃磁盘但是不吃内存，会提高兼容性这样，就可以留着。

因为我也不懂这个精简windows的门道，所以就是比较啰嗦。

最后，谢谢大佬。

**Comment by WhatTheBlock** [comment]
我對極限精簡得定義是將WinSxS移除，換句話說這種情況下Windows Update將會失去作用，特別適合完全不想更新的人

當然實際使用上還是需要你幫忙測試，有問題的話再麻煩回報讓我修復了

**Comment by ChaunceyShannon** [comment]
好的。感谢。

**Comment by WhatTheBlock** [comment]
![Snipaste_2022-05-05_16-47-10](https://user-images.githubusercontent.com/34786954/166890397-5436b901-7630-439e-b9a5-eb4ab24006c8.png)

運行Unity + WSL 1的演示圖

**Comment by WhatTheBlock** [comment]
請問你輸入法是使用哪一款呢？

由於Windows Update被移除，因此後續要再安裝微軟拼音就會失敗

如果只有使用微軟拼音的話就必須要改用簡中映像製作了

**Comment by WhatTheBlock** [comment]
![Snipaste_2022-05-05_19-18-49-min](https://user-images.githubusercontent.com/34786954/166913467-426eed28-d2c4-4ae7-842b-981c9d8b5dc8.png)

**Comment by ChaunceyShannon** [comment]
> 請問你輸入法是使用哪一款呢？
> 
> 由於Windows Update被移除，因此後續要再安裝微軟拼音就會失敗
> 
> 如果只有使用微軟拼音的話就必須要改用簡中映像製作了

真是抱歉啊，没有及时回复。真的是我会用微软拼音。

不过，我也可以使用鼠须管来解决咯。

谢谢你。

**Comment by ChaunceyShannon** [comment]
大佬大佬。这个系统的github的那个下载链接挂了诶。是404呢。

**Comment by WhatTheBlock** [comment]
> 大佬大佬。这个系统的github的那个下载链接挂了诶。是404呢。

我現在只有上傳OneDrive 😂

**Comment by ChaunceyShannon** [comment]
> > 大佬大佬。这个系统的github的那个下载链接挂了诶。是404呢。
> 
> 我現在只有上傳OneDrive joy

哈。下载下来了。谢谢大佬。还给准备了英文的。

不过有个问题呢。安装firefox的时候不知道为什么会报这个memory的错误

![image](https://user-images.githubusercontent.com/87258078/167092134-0141eaad-8181-429b-b44e-c24bc1a25d52.png)

用的是这个安装程序 https://download-installer.cdn.mozilla.net/pub/firefox/releases/100.0/win64/en-US/Firefox%20Setup%20100.0.msi

VMWare的相关信息如下

![image](https://user-images.githubusercontent.com/87258078/167092271-036b3b04-23e2-4361-b885-c1d8e1113dea.png)

![image](https://user-images.githubusercontent.com/87258078/167092391-c9c10247-1f90-4eb3-80ee-8dca4e73c186.png)

**Comment by ChaunceyShannon** [comment]
尝试使用exe也是这样

https://download-installer.cdn.mozilla.net/pub/firefox/releases/100.0/win64/en-US/Firefox%20Setup%20100.0.exe

![image](https://user-images.githubusercontent.com/87258078/167094270-2542936f-49d2-40f2-8b39-a9957a2dec9c.png)

**Comment by ChaunceyShannon** [comment]
不过

> 尝试使用exe也是这样
> 
> https://download-installer.cdn.mozilla.net/pub/firefox/releases/100.0/win64/en-US/Firefox%20Setup%20100.0.exe
> 
> ![image](https://user-images.githubusercontent.com/87258078/167094270-2542936f-49d2-40f2-8b39-a9957a2dec9c.png)

不过桌面上有firefox的图标，点击是可以运行的，我在装chrome，稍后装office，再测测看。

**Comment by ChaunceyShannon** [comment]
测试chrome，git，vscode，openvpn，7zip，wsl1，没有问题。

安装office的时候，在它安装onedrive的时候又报错内存问题

![image](https://user-images.githubusercontent.com/87258078/167096385-c52ee642-18f0-4144-98a7-782c77099597.png)

不过它似乎并不影响我使用word，excel，ppt之类的程序。

**Comment by ChaunceyShannon** [comment]
测试安装rime输入法也没有问题。

准备开几个程序长期开机看看会不会有额外的问题啦。

**Comment by WhatTheBlock** [comment]
這問題我也不知道是什麼條件導致的

如果有影響到程式運作再麻煩回報了
