### ISSUE TITLE
USBCCID driver 未來是否可以加進去極度精簡版

### ISSUE THREAD

**Issue by fatdenny** [WhatTheBlock/WindowsSimplify#25]
回報一個驅動缺失 , 目前已經先用普通版本頂上了 ，謝謝製作ISO。

Win10_LTSB_14393.0_210804 (極度精簡版)x64

![](https://i.imgur.com/XtlRseJ.png)

![](https://i.imgur.com/naeWDHr.png)

之前用過這個版本是可以正常運行的 

https://archive.org/details/windows-10-lite-edition-19h2-x64

**Comment by WhatTheBlock** [comment]
我這個版本確實移除掉smartcard相關組件和驅動了
下次更新會補上
