### ISSUE TITLE
22000.593_220404不能點左下角開始按鈕

### ISSUE THREAD

**Issue by JimmyHsu285** [WhatTheBlock/WindowsSimplify#26]
Hi sir
22000.593_220404 這個版本沒法點左下角開始按鈕,  點下去沒反應...
我測試的平台:
H610+ Core i3-12100 + DDR4 8G*2

**Comment by WhatTheBlock** [comment]
這是因為ExplorerPatcher在更新組件，請確保網路正常聯網，更新完畢後須重啟explorer.exe
![1](https://truth.bahamut.com.tw/s01/202204/c2a3db5f3d4841fe3f7d6c7cad659d59.PNG)
![2](https://truth.bahamut.com.tw/s01/202204/4a708dab4f0c2d724668e529e898c0bf.PNG)
