### ISSUE TITLE
WIN11在VirtualBox運行時非常卡頓

### ISSUE THREAD

**Issue by clc0321** [WhatTheBlock/WindowsSimplify#30]
![failed](https://user-images.githubusercontent.com/94593182/174949762-1ae9a40a-8125-42aa-b2da-2f96cf3e3c6e.png)
他就這樣一直卡住，無法安裝系統，即使重來也一樣
然後過不久就變這樣
![image](https://user-images.githubusercontent.com/94593182/174950038-ec21e68f-3e54-4d38-b9b6-c6c7d1b76dec.png)
換成win10就可以正常運行不會卡頓
不知道是哪裡出問題了

**Comment by WhatTheBlock** [comment]
我主要都是用VMware測試，virtualbox有時要改一些設定才能正常安裝
