### ISSUE TITLE
請問一下帶wsl的精簡版本的win11有集成VirtIO驅動嗎

### ISSUE THREAD

**Issue by darren2046** [WhatTheBlock/WindowsSimplify#31]
因爲我想要在vps上面安裝使用，上傳ISO的控制面板提示說windows需要集成VirtIO驅動程式才能正常運作，所以請問一下有集成嗎？非常感謝。

**Comment by WhatTheBlock** [comment]
沒有喔，目前win11還沒製作過集成virtio的版本

**Comment by darren2046** [comment]
我看到網上有人提供可以直接在linux使用dd命令來寫入磁盤的windows鏡像，這個安裝就很方便。哈。不知道您有沒有興趣呢？如果這樣的話，在vps上面安裝windows就特別簡單了。 例如 curl http://example.com/win.img > /dev/sda

**Comment by smt311** [comment]
可以自行加驅動到ISO 影像檔內
