### ISSUE TITLE
無法安裝minecraft啟動器和透明效果失效

### ISSUE THREAD

**Issue by alex199908** [WhatTheBlock/WindowsSimplify#33]
在VMBOX上 無法使用透明效果 

從官方下載的ISO可以顯示透明效果

另外無法安裝minecraft的啟動器

**Comment by WhatTheBlock** [comment]
麻煩提供所使用的iso檔案名稱，謝謝

**Comment by alex199908** [comment]
22621.105_220617

**Comment by WhatTheBlock** [comment]
謝謝，請教一下啟動器無法安裝有錯誤訊息的截圖可以提供嗎？

**Comment by alex199908** [comment]
![圖片](https://user-images.githubusercontent.com/109454381/179938565-8d47c877-08a0-422c-aab3-be670e3a3d94.png)

**Comment by WhatTheBlock** [comment]
你好，麻煩幫我測試看看復原包是否能修復minecraft的錯誤
[https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/restore-pack](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/restore-pack)

**Comment by alex199908** [comment]
謝謝

**Comment by alex199908** [comment]
那個透明效果又正常出現了 真的超詭異

**Comment by WhatTheBlock** [comment]
會不會是當時沒有安裝好顯卡驅動
因為顯卡驅動沒裝時系統會自動關閉部分效果顯示

**Comment by alex199908** [comment]
那個 恢復包無法使用欸
![圖片](https://user-images.githubusercontent.com/109454381/181768612-ce8ceafc-c146-4153-b162-64e982eac39e.png)
![圖片](https://user-images.githubusercontent.com/109454381/181768639-4d81f090-aa8f-4d4d-bfb0-20e3c98031c5.png)

**Comment by WhatTheBlock** [comment]
你好，新版系統已經為復原包做適配，並修正xbox無法使用的問題，近期會上傳發布

**Comment by alex199908** [comment]
謝謝

**Comment by alex199908** [comment]
請問能做11版的嗎

**Comment by WhatTheBlock** [comment]
win11也會製作，不用擔心

**Comment by WhatTheBlock** [comment]
已上傳完畢

[Link](https://gmnfuedutw-my.sharepoint.com/:u:/g/personal/40543229_gm_nfu_edu_tw/ES76XSvFq6xPgxf7QHS5BmIBGsmxSBAWfT04QfdY0VaiAA?e=LWPbDP)
