### ISSUE TITLE
極度精簡版 Chrome 執行出錯 (RESULT_CODE_MISSING_DATA)

### ISSUE THREAD

**Issue by cj-neo** [WhatTheBlock/WindowsSimplify#37]
測了兩台電腦都一樣，無法看到歡迎畫面、無法設定、無法瀏覽網頁，但使用微軟的 ie 或 edge 就正常

![image](https://user-images.githubusercontent.com/35209118/184787202-13e05982-d84b-40c3-9dfa-3879a3692d46.png)

**Comment by WhatTheBlock** [comment]
極度精簡版已經有點舊了，未來會找時間重新製作，順便修復已知問題，謝謝

**Comment by WhatTheBlock** [comment]
將`chrome.exe`使用Windows 8相容性模式執行即可解決

![1](https://raw.githubusercontent.com/WhatTheBlock/WindowsSimplify/master/tutorial/fix_rcmd.png)
