### ISSUE TITLE
關於 RDP 遠端連線功能

### ISSUE THREAD

**Issue by cj-neo** [WhatTheBlock/WindowsSimplify#38]
您好

請問是不是所有版本的 RDP 遠端連線都被閹割掉了，
因為精簡版很適合裝在比較低階的伺服器電腦上，
這個功能還蠻需要的說，不知道有沒有辦法手動加回來。

謝謝

**Comment by WhatTheBlock** [comment]
穩定版並沒有精簡掉這個組件，如果因為效能的問題需要再進一步精簡請額外開一個issue提出訂製需求，謝謝

**Comment by cj-neo** [comment]
您好小弟安裝 Stable 1.75GB (Ver.2) 這個版本沒看到有開啟 RDP，到服務裡面看也沒有，還是 Ver.1 版本才有，謝謝 @@"

**Comment by WhatTheBlock** [comment]
ver.2都是以ver.1為基礎再做進一步的精簡，需要使用到較少人用的功能都建議安裝ver.1

另外，我猜你安裝的應該是win10 pro的穩定版，建議優先考慮最新製作的ltsc 2021

**Comment by cj-neo** [comment]
好的感謝！剛下載 ver.1 好像也沒有 RDP 我再試試看 ltsc 2021 好了， 因為安裝精簡版希望越簡單越好，所以之前都盡量找容量小的 XD
