### ISSUE TITLE
en-us build

### ISSUE THREAD

**Issue by EDK-Rise** [WhatTheBlock/WindowsSimplify#41]
could you make your builds in en-us?

**Comment by WhatTheBlock** [comment]
Of course, which version do you need? (ISO file name)

**Comment by EDK-Rise** [comment]
[LTSC_19044](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/ltsc.220722) with latest update (1889)

**Comment by WhatTheBlock** [comment]
![Snipaste_2022-08-27_07-30-17](https://user-images.githubusercontent.com/34786954/187002772-cf0bd702-84ff-4dd3-ba97-1ddd59c47876.png)

**Comment by WhatTheBlock** [comment]
## Extreme Lite version
![Snipaste_2022-08-28_07-32-28](https://user-images.githubusercontent.com/34786954/187051509-af22086f-2a6d-44b3-9667-df6f6a3188d7.png)

**Comment by WhatTheBlock** [comment]
Stable: [Link](https://gmnfuedutw-my.sharepoint.com/:u:/g/personal/40543229_gm_nfu_edu_tw/Eel0vC_A6DJAvZWrrLQChaUB_omXog-91eEAVjajs1o7zQ?e=umofiB)

Extreme Lite: [Link](https://gmnfuedutw-my.sharepoint.com/:u:/g/personal/40543229_gm_nfu_edu_tw/EctfZvX1qPhJjf6WejA8ZFEBtWU2jXfzyymQsVpEImCBLA?e=8KGAZ8)

**Comment by Suleman-Elahi** [comment]
There is no English verion for 2022/08/11 Windows 11 Pro OS Build: 22621.317 on this page: [tree/master/11](https://github.com/WhatTheBlock/WindowsSimplify/tree/master/11). Is there a plan for Eng version?

**Comment by WhatTheBlock** [comment]
> There is no English verion for 2022/08/11 Windows 11 Pro OS Build: 22621.317 on this page: [tree/master/11](https://github.com/WhatTheBlock/WindowsSimplify/tree/master/11). Is there a plan for Eng version?

Yes, English version will be released gradually.

**Comment by Suleman-Elahi** [comment]
k thanks :)

**Comment by WhatTheBlock** [comment]
> There is no English verion for 2022/08/11 Windows 11 Pro OS Build: 22621.317 on this page: [tree/master/11](https://github.com/WhatTheBlock/WindowsSimplify/tree/master/11). Is there a plan for Eng version?

@EDK-Rise @Suleman-Elahi 
English version out now!
![1](https://raw.githubusercontent.com/WhatTheBlock/WindowsSimplify/master/preview/22621.521_220917.png)

[Release page](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.220917)

**Comment by Suleman-Elahi** [comment]
> English version out now!

Thanks a ton. Waiting for Win 10 and 8.1 en-us version well in the coming updates.

**Comment by WhatTheBlock** [comment]
> > English version out now!
> 
> Thanks a ton. Waiting for Win 10 and 8.1 en-us version well in the coming updates.

ok, stay tuned.
