### ISSUE TITLE
是否可以製作 Windows 11 家用版  的精簡版本

### ISSUE THREAD

**Issue by lalarun** [WhatTheBlock/WindowsSimplify#42]
相信有一部份的人，買電腦時，附贈的作業系統
是 Windows 11 家用版，因此，合法的啟動序號
也只能用在家用版

是否考慮製作，以  Windows 11 家用版  的精簡版本
讓電腦原有的啟動序號，可以正常使用

**Comment by WhatTheBlock** [comment]
可以，但優先度較低，目前會先多製作幾個英文版系統讓國外用戶使用
