### ISSUE TITLE
請問，Windows 11 的 Ver.1  和 Ver.2，功能上有何區別

### ISSUE THREAD

**Issue by lalarun** [WhatTheBlock/WindowsSimplify#43]
想請教作者：

Windows 11 每個版本，都有區分 Ver.1  和 Ver.2，功能上、穩定度，二者有何區別？
(很抱歉這個問題可能有點基本，請多多包涵新手上路)

**Comment by WhatTheBlock** [comment]
Ver.1為穩定版本，Ver.2則是以Ver.1為基礎再精簡部分組件

基本上每次發布的Ver.2的精簡方式都不一樣，我常會用來測試新的製作方式

最直覺的判斷方式就是檔案大小，如果使用需求是非常基本的上網、文書處理，那Ver.2一樣很穩定

當然，最保險的做法仍然是先使用虛擬機測試是否符合自己的使用需求
