### ISSUE TITLE
Xbox無法使用，WSA如何啟動Google Play

### ISSUE THREAD

**Issue by Coolbee0618** [WhatTheBlock/WindowsSimplify#45]
我裝了你(妳)製作的WSA，成功進系統後嘗試裝了Xbox但裝好後出現了如下圖的錯誤訊息，並且嘗試登入後有跳出一個灰色視窗，然後就跳回去Xbox首頁，沒有登入，該如何解決，並且我也想問怎麼啟動Google Play，我不識很懂這方面的東西，抱歉（ˊ • ω • ˋ ）
![螢幕擷取畫面 (1)](https://user-images.githubusercontent.com/115006848/193830891-3178142e-3b49-4d7f-954a-afdbf4065434.png)

**Comment by WhatTheBlock** [comment]
謝謝回報，我會找時間測試

這幾天要換電腦，會停更一小段時間
