### ISSUE TITLE
Windows 11 ARM64 feedback

### ISSUE THREAD

**Issue by hudsonhu** [WhatTheBlock/WindowsSimplify#47]
Thank you for your hard work!! Here are some feedback of arm64 version:

Windows 11 220829.iso cannot be installed, and stuck after one reboot, showing this:
<img width="708" alt="截屏2022-10-18 21 22 52" src="https://user-images.githubusercontent.com/48980398/196441798-06a15f00-c6dc-426a-a61c-e8b0786dcb33.png">

Version 220722 worked fine, tested in my Parallels Desktop 18 vm.

It would be great if you can release an ARM64 Windows 11 which removes Windows Update, I would be very happy to participate testing.

**Comment by WhatTheBlock** [comment]
22621.232_arm_220829 has removed windows update.
The bug of specialize has been fixed and the file is uploading.

**Comment by WhatTheBlock** [comment]
[22621.232_arm_221018.part1.rar](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/iso/22621.232_arm_221018.part1.rar)
[22621.232_arm_221018.part2.rar](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/iso/22621.232_arm_221018.part2.rar)

**Comment by hudsonhu** [comment]
It works, thank you!

**Comment by WhatTheBlock** [comment]
@hudsonhu 
Hi! Can you provide the running screen of 22621.232_arm_221018 for the release page?
Thanks!

**Comment by hudsonhu** [comment]
Sure, I will be happy to participate in the testing of the new version.
<img width="1440" alt="10" src="https://user-images.githubusercontent.com/48980398/197098216-d28909c4-f0c8-4489-8944-35ba6689b9e5.png">
