### ISSUE TITLE
Windows7 Lite. advice

### ISSUE THREAD

**Issue by LilyJone** [WhatTheBlock/WindowsSimplify#51]
Hello developers.

Use the windows Lite you made many times. But most of the time there are errors, or the system is too small and lacks a lot of suite.
There is a nice windows lite system by the author name naifle. It's the most stable and compatible streamlined system I've ever seen. Is there a way you can modify it in multiple languages? It is a pity that only Russian is supported. To English, simplified Chinese, traditional Chinese...

https://github.com/LilyJone/OpenTools/releases/tag/Windows7

**Comment by WhatTheBlock** [comment]
What are your functional requirements?
If there are reproducible errors, welcome to report, thank you!

**Comment by WhatTheBlock** [comment]
This system has removed compatibility with installed language packs, so modifications to multilingual versions are not possible.

**Comment by WhatTheBlock** [comment]
This version refers to the removed components of the system made by naifle.
Welcome to report if there are errors.

[7601.26174_MultLang_221127](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w7.221128)
