### ISSUE TITLE
arm win11 可否添加打印机组件

### ISSUE THREAD

**Issue by zhanker** [WhatTheBlock/WindowsSimplify#52]
感谢分享精简系统，我下载安装后，想了好几个办法恢复打印机组件没有办法，希望能出一版有打印机组件的精简系统！

**Comment by WhatTheBlock** [comment]
好的，由於製作ARM版的預設立場是用於虛擬機或是樹梅派之類的開發版，所以才沒有保留列印功能

**Comment by zhanker** [comment]
apple m1 ，Parallels Desktop 17 下运行测试没问题。我在全网搜索，您制作的精简版，完成度是最高的。

**Comment by WhatTheBlock** [comment]
謝謝支持 🥰

**Comment by WhatTheBlock** [comment]
已製作完畢
[22621.900_arm_221205](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.arm.221205)

**Comment by zhanker** [comment]
这个版本与上版相比，无法添加语言包 ，我这里使用简体中文，无法调用Microsoft VBA 模块，无法安装office 365。测试了好几个版本，只有最初一版（7月份）可以同时拥有添加语言包及打印机功能。

**Comment by zhanker** [comment]
系统语言（英文）与离线安装office 2019（中文）语言不一致，excel vba 表格出现大量错误，无法使用。其他一般程序测试正常，最好的是保留添加语言包功能。

**Comment by zhanker** [comment]
我了解到可以自行搜索Microsoft Store，下载离线安装包,包含语言包：https://store.rg-adguard.net/
虽然无法在线安装office 365，但是其他离线版本可以正常使用。
<img width="1568" alt="Snipaste_2022-12-13_10-31-43" src="https://user-images.githubusercontent.com/20961577/207215181-340c5cb2-2713-42be-a701-5d57757b8433.png">
