### ISSUE TITLE
简体中文语言包

### ISSUE THREAD

**Issue by wzslrb** [WhatTheBlock/WindowsSimplify#53]
win7 pro 怎么安装简体中文语言包 或设置显示简体中文
桌面 资源管理器菜单 全是繁体中文
在控制面板更改语言和地区为中文简体也不管用

**Comment by WhatTheBlock** [comment]
win7 pro本身並不支援安裝語言包，有需要我再製作一個簡體版就好

**Comment by WhatTheBlock** [comment]
已製作完畢
[7601.26174_cn_221204](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w7.221204)
