### ISSUE TITLE
Windows10 Enterprise LTSC 2019 x64無法打開救援模式

### ISSUE THREAD

**Issue by tiujejauci** [WhatTheBlock/WindowsSimplify#54]
版本：[Enterprise LTSC 2019 x64](https://github.com/WhatTheBlock/WindowsSimplify/blob/master/10/README.md#ltsc-2019-x64 ) 
型號：Windows10 ( 17763.2803)
ISO Size： 2.78GB
連結： [Part 1](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/ltsc.220424/LTSC_17763.2803_220424.part1.rar)、[Part 2](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/ltsc.220424/LTSC_17763.2803_220424.part2.rar)
SHA-256： 1f11b2f9125c2c268cba0c57101f05c11ace771d74e827ceced03ec426a38636
問題：安裝[華碩TUF GAMING B550M-PLUS WIFI II](https://www.asus.com/motherboards-components/motherboards/tuf-gaming/tuf-gaming-b550m-plus-wifi-ii/helpdesk_download/) 的[SATA驅動](https://dlcdnets.asus.com/pub/ASUS/mb/SocketAM4/TUF_GAMING_B550-PLUS_WIFI_II/AMD_RAID_Driver_V9.3.0.266_WIN10_64-bit.zip ) ，
 重啟無法進入桌面，開機狂按F8亦未能進入救援模式，需要幫助。

**Comment by tiujejauci** [comment]
![IMG_20221213_154133~01~01](https://user-images.githubusercontent.com/31369434/207322048-7521d2d6-14c9-41b4-88bc-b6d660aafb8d.jpg)
開機不斷顯示此畫面並自動重啟，無法進入桌面。

**Comment by WhatTheBlock** [comment]
你有改過bios的任何設定嗎？
如果有就進bios還原預設

另外win10本來就不支援F8
開機多失敗幾次會自動出現是否進入安全模式的選項
但你的問題可能是電腦沒辦法正確讀取系統硬碟

**Comment by tiujejauci** [comment]
> 你有改過bios的任何設定嗎？ 如果有就進bios還原預設
> 
> 另外win10本來就不支援F8 開機多失敗幾次會自動出現是否進入安全模式的選項 但你的問題可能是電腦沒辦法正確讀取系統硬碟

它3點半自動重啟到5點還沒有停，

**Comment by tiujejauci** [comment]
> 你有改過bios的任何設定嗎？ 如果有就進bios還原預設
> 
> 另外win10本來就不支援F8 開機多失敗幾次會自動出現是否進入安全模式的選項 但你的問題可能是電腦沒辦法正確讀取系統硬碟

BIOS也是預設，開了SVM虛擬化

**Comment by WhatTheBlock** [comment]
你先重裝一次系統，raid驅動使用amd官網的最新版試試
