### ISSUE TITLE
request

### ISSUE THREAD

**Issue by mxxtthias** [WhatTheBlock/WindowsSimplify#56]
could you make this [build](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.230102) in en-us or es-es please?

**Comment by daBroma** [comment]
Yeah I'd love to see that build in English too, also I'd suggest to directly put ISO download links instead of rar archives since I tried countless of programs and still couldn't extract them. Maybe try the .7z format. Would really like to see all builds have a cn and en build.

**Comment by WhatTheBlock** [comment]
> I'd suggest to directly put ISO download links instead of rar archives since I tried countless of programs and still couldn't extract them. Maybe try the .7z format.

I use WinRAR and 7-Zip to extract the ISO file without any problem, and the ISO can be directly used to make a USB boot or virtual machine boot.

**Comment by daBroma** [comment]
Weird, might've found my issue now. But yeah English builds would be appreciated. Especially for https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.230102 .

**Comment by mxxtthias** [comment]
thanks!
