### ISSUE TITLE
bitlocker 使用問題

### ISSUE THREAD

**Issue by qtfp** [WhatTheBlock/WindowsSimplify#57]
![image](https://user-images.githubusercontent.com/4852521/212213713-dfab72c6-104f-4ff4-8e64-5266a7e82ee7.png)
最近安裝這版覺得真的很厲害
不過因為是裝在surface pro8 會帶出去 需要使用bitlocker 請問這個有辦法做甚麼調整就可以加上去嗎

**Comment by WhatTheBlock** [comment]
bitlocker已移除，需要重新製作才能用
