### ISSUE TITLE
無法安裝累積更新 Windows 10 LTSC 2021 x64 

### ISSUE THREAD

**Issue by wongwengtim** [WhatTheBlock/WindowsSimplify#58]
Edition： Enterprise LTSC 2021

OS Build： 19044.2075

錯誤提示：安装更新時發生一些問題,但我們再稍後再試一次,若您持續者到此訊息,且想要搜尋網路或連絡支援人員以取得詳細資訊,這可能有所幫助:(0x80242fff)

2023-01 適用於 x64 系統 Windows 10 Version 21H2 的累積更新 (KB5022282)
無法在 2023/1/14-0x800f081f 上安装

嘗試從Windows Update Catalog下載 同樣無法手動安裝

**Comment by wongwengtim** [comment]
另外此（1月10日，微軟發佈此累積更新）前也無法安裝 2022-12 的累積更新

**Comment by WhatTheBlock** [comment]
我製作的系統都不支援windows update
想要安裝更新就不該使用精簡版系統
兩者無法兼具
