### ISSUE TITLE
LTSC 2021 x64 更新檔（KB5022282）無法安裝

### ISSUE THREAD

**Issue by ytalai** [WhatTheBlock/WindowsSimplify#59]
請問穩定版是否無法進行win更新???

裝了兩三台電腦
也重做過安裝碟
只要是遇到KB5022282這個更新
就肯定會失敗
測試過直接下載更新檔單獨安裝也是失敗

![IMG_0632](https://user-images.githubusercontent.com/122670300/212465447-c64f22bd-79fa-475d-9b96-066b1048be89.jpg)
![IMG_0631](https://user-images.githubusercontent.com/122670300/212465466-4f205884-3898-47e7-8bb3-5f935536373f.jpg)

**Comment by WhatTheBlock** [comment]
我製作的系統都不支援windows update
想要安裝更新就不該使用精簡版系統
兩者無法兼具
