### ISSUE TITLE
Windows 11 ARM64 discussions

### ISSUE THREAD

**Issue by liuly23** [WhatTheBlock/WindowsSimplify#60]
你好，我在小米平板5上测试安装了最新的win11 arm镜像，非常好用，比我在uupd上下载的原版镜像系统占用少了20gb，但是我发现两个问题：一是无法添加中文语言包（如果您还继续维护此项目的话，可以在下个版本添加中文语言包吗，谢谢），二是无法打开Windows Store。最后，谢谢您的付出。❤️😘
你好，我在小米平板5上測試安裝了最新的win11 arm鏡像，非常好用，比我在uupd上下載的原版鏡像系統占用少了20gb，但是我發現兩個問題：一是無法添加中文語言包（如果您還繼續維護此項目的話，可以在下個版本添加中文語言包嗎，謝謝），二是無法打開Windows Store。最後，謝謝您的付出。❤️😘

**Comment by WhatTheBlock** [comment]
沒問題

希望製作完您可以提供使用截圖

因為我製作ARM64都是沒有經過任何測試的

**Comment by liuly23** [comment]
好的，再次感謝！
![Snipaste_2023-01-15_21-56-36_LI](https://user-images.githubusercontent.com/122763186/212609328-3cfe314d-ca88-492a-a013-c61699f33359.jpg)

**Comment by liuly23** [comment]
您好，剛剛截圖時發現個新問題，即圖片無法用Windows自帶的Photos打開

**Comment by WhatTheBlock** [comment]
那內建的傳統圖片檢視器可以使用嗎？
圖片的檔案關聯是否可以設定要使用的程式？

**Comment by kero990** [comment]
我想說的是，請問是否可以保留edge呢
全新安裝的lv1，既沒有商店，也沒有edge，這導致即使鏈接網絡是成功的，也沒有任何程序能夠打開網頁，甚至沒有任何程序能夠在本機下載一個edge，這很尷尬。

**Comment by WhatTheBlock** [comment]
> 我想說的是，請問是否可以保留edge呢 全新安裝的lv1，既沒有商店（我不確定商店補充包是否適用於arm64），也沒有edge，這導致即使鏈接網絡是成功的，也沒有任何程序能夠打開網頁，甚至沒有任何程序能夠在本機下載一個edge，這很尷尬。而且arm64的edge似乎並沒有網頁下載鏈接（至少我沒搜到），似乎仍然需要商店安裝。

請參考以下片段：
[youtube](https://youtu.be/KHYg8D0l_eg?feature=shared&t=617)

如果你有先看完demo影片就不會有這個問題了，是吧？
