### ISSUE TITLE
Remote Deskop Services 增加

### ISSUE THREAD

**Issue by calebweixun** [WhatTheBlock/WindowsSimplify#61]
您好，我正在使用您所製作的系統，版本：
 [22623.1028_atlas_230102](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.230102)
目前安裝於實驗室的電腦設備中，想問有任何的方式可以將遠端桌面服務安裝回來嗎？

謝謝

**Comment by WhatTheBlock** [comment]
這個需要重新製作
我下個版本再檢查一下

**Comment by calebweixun** [comment]
剛剛查了一下，AtlasOS 預設是有移除 Remote Desktop 的，可以在[FQA](https://github.com/Atlas-OS/Atlas/wiki/1.-FAQ)看到。
期待您的下個版本，目前的版本相當好用，謝謝。

**Comment by calebweixun** [comment]
剛剛要使用自然人憑證時發現沒有 Smart Card 服務，也無法安裝讀卡機驅動，錯誤為不存在裝置類別。

**Comment by WhatTheBlock** [comment]
是的，因為這項已經移除了
是否保留這項功能我再想一下
會使用到的人太少了（指精簡系統同好）

**Comment by WhatTheBlock** [comment]
你好，新版系統有保留這兩種組件，麻煩你測試看看
