### ISSUE TITLE
Win11 ARM64 简体中文版

### ISSUE THREAD

**Issue by julystars** [WhatTheBlock/WindowsSimplify#62]
非常好👍！
mac上测试了win11 ARM64 2022/12/05，优化了6个G的空间。
能否出一个Win11 ARM64 简体中文版，非常感谢。

**Comment by WhatTheBlock** [comment]
目前有嘗試要做多語言版本

避免每次都要分別上傳檔案

製作完畢會再通知你，謝謝支持

**Comment by byteat** [comment]
6月上传的那个arm64版看起来功能都已经可以了，就缺中文了😘

**Comment by fwycxm** [comment]
> 6月上传的那个arm64版看起来功能都已经可以了，就缺中文了😘

安装后 在语言里添加中文就好啦
