### ISSUE TITLE
無法登入 OneDrive

### ISSUE THREAD

**Issue by terry3041** [WhatTheBlock/WindowsSimplify#63]
我是在用 Win11 22623.1028_atlas_230102
用 OneDrive 登入學校帳號的時候顯示“錯誤 1001”
用 Windows 設定 > 存取公司或學校資源 > 新增公司或學校帳號則會顯示“發生錯誤”
請問有解決方法嗎？

**Comment by WhatTheBlock** [comment]
你試試從store登入帳號，我影片中大約7：30的地方有測試登入帳號並沒有問題

**Comment by terry3041** [comment]
> 你試試從store登入帳號，我影片中大約7：30的地方有測試登入帳號並沒有問題

會顯示“該 Microsoft 帳戶不存在”
學校 / 公司帳號應該是 Sharepoint 的帳號
跟普通的 Microsoft 帳號不一樣

**Comment by WhatTheBlock** [comment]
好的，我再找時間測試我自己的學術帳號

**Comment by ifloppy** [comment]
> 好的，我再找時間測試我自己的學術帳號

想请问一下该问题是否已经得到了缓解。我正在使用 Windows 10 Pro 19045.2486 c6e434babeee0cd92e0c42e419b489ae435066ee8e274748574649aa77390902，在Microsoft 365和OneDrive中都无法登入工作账户，但是能够正常登入个人账户。
