### ISSUE TITLE
Steps to Restore Recovery Environment

### ISSUE THREAD

**Issue by Suleman-Elahi** [WhatTheBlock/WindowsSimplify#68]
Hi, I am using Windows 10 Lite, and I am stuck as I enabled secure boot. Now, I cannot access the BIOS menu. Since this Windows doesn't have Recovery Environment, how do I fix this?

![Screenshot (1)](https://user-images.githubusercontent.com/24384996/221182658-c42c03c8-a8f6-46af-b043-8f3f03960274.png)

Is there a way to install WinRE in Windows 10 manually now?

**Comment by WhatTheBlock** [comment]
Try clearing the BIOS CMOS. Resetting the BIOS to default should work.

**Comment by Suleman-Elahi** [comment]
> Try clearing the BIOS CMOS. Resetting the BIOS to default should work.

But for that, I will have to open my laptop. I don't have the tools and I am not keen to open up my laptop.

**Comment by WhatTheBlock** [comment]
I don't understand why you can't enter the BIOS. Is it that you enter the Windows boot process without even displaying the brand logo? After turning on the power, even if the screen is not displayed, clicking the common shortcut keys such as Del or F1~F12 does not work?

**Comment by Suleman-Elahi** [comment]
> I don't understand why you can't enter the BIOS. Is it that you enter the Windows boot process without even displaying the brand logo? After turning on the power, even if the screen is not displayed, clicking the common shortcut keys such as Del or F1~F12 does not work?

Yes, it is the problem with Lenovo Laptops. Usually, BIOS opens with F2. But once you turn on secure boot and fastboot then the only way to enter BIOS is though UEFI Firmware Settings option that appears in the Recovery Environment.

This option:

![image](https://user-images.githubusercontent.com/24384996/221754818-1f726c45-3075-42b9-998d-ff41e1fa4f21.png)

Anyway, I think I found solution.
