### ISSUE TITLE
为啥没有无线呢？

### ISSUE THREAD

**Issue by xp12047** [WhatTheBlock/WindowsSimplify#69]
装上的时候很开心。真的好干净。但是只有蓝牙没有无线了？最新的版本

**Comment by WhatTheBlock** [comment]
網卡驅動需要自行安裝，請參考demo影片

因win11自帶太多網卡驅動，所以比較建議配合3dp安裝指定的驅動避免浪費空間

**Comment by xp12047** [comment]
> 网卡驱动需要自行安装，请参考演示影片
> 
> 由于win11自带太多网卡驱动，所以比拟建议配合3dp安装指定的驱动避免免费浪花空间
谢谢
