### ISSUE TITLE
WSA English

### ISSUE THREAD

**Issue by jujion** [WhatTheBlock/WindowsSimplify#71]
Hi, I can't change the language on Windows 11 WSA to English, as some of the components remain unchanged. Is there any WSA build that has English as the default language?

**Comment by WhatTheBlock** [comment]
Sorry, WSA build temporarily stop updating.
However, the multilingual version has been tested and works, so the next update will provide a multilingual version.

**Comment by jujion** [comment]
Thank you very much!

**Comment by jujion** [comment]
Thanks very much! Is there an ETA for the next update?

**Comment by WhatTheBlock** [comment]
I'm not sure, but I'm keeping track of WSA updates. If performance can rival the Android emulator. I'd love to update for that.
