### ISSUE TITLE
微软商店安装软件出现0x80070005错误

### ISSUE THREAD

**Issue by dr-ameba** [WhatTheBlock/WindowsSimplify#72]
版本是Windows 11 Pro 22623.746，安装在Hyper-V上
在微软商店试了好几个软件都下载不了，连自家Edge浏览器都无法安装，安装时显示“无法安装此应用程序，检查Microsoft Store更新，然后再试一次”以及0x80070005错误，按照指示更新后也不行，把商店程序重置了也不可以
暂时发现唯有Firefox可以安装，也可以对已有的程序进行更新，应该不是网络问题，而且之前装不了的程序在物理机上是可以正常安装的（Windows 10 Pro）
0x80070005错误看了一圈都没有能解决的办法，不知道有没有可能是因为精简了更新组件，实在没有头绪（那这样精简的话留微软商店还有意义吗😂）

**Comment by WhatTheBlock** [comment]
Store的部分比較麻煩，因為Store的更新頻率高，當下製作時測試可用沒辦法保證未來也能正常運作 

至於保留Store的意義在於部分人有使用Xbox組件的需求，透過Store更新較方便
