### ISSUE TITLE
English Windows 7 and 8.1

### ISSUE THREAD

**Issue by Suleman-Elahi** [WhatTheBlock/WindowsSimplify#73]
Please add English versions of Windows 7 and Windows 8.1

**Comment by WhatTheBlock** [comment]
English versions of windows 7:
[Win7_Pro_(7601.17514)_en_20210423-2](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/v2021.04.23_en_2)

**Comment by WhatTheBlock** [comment]
Multilingual versions of windows 8.1:
[9600.20778_Multilingual_230509](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w8.230509)
