### ISSUE TITLE
Updated Windows 11 ARM Build

### ISSUE THREAD

**Issue by falchion10** [WhatTheBlock/WindowsSimplify#75]
Could we get an updated Windows 11 ARM Build? It's been almost half a year since we've seen a new release. Potentially to build 25357 on the Canary branch to keep things fresh for awhile?

**Comment by WhatTheBlock** [comment]
Ok, I'm going to try to build a 25357.1.

**Comment by BienGudBoy** [comment]
Is it possible to upgrade from one version to newer btw? It kinda sucks to reinstall everything

**Comment by falchion10** [comment]
I don't think that would be possible, when you update Windows manually a lot of the removed stuff gets re-added and the OS gets re-bloated. Unfortunately you'll need to do a reinstall.

**Comment by WhatTheBlock** [comment]
> Is it possible to upgrade from one version to newer btw? It kinda sucks to reinstall everything

It is recommended to keep the rule of keeping important data and software outside the system partition. There is not much to lose by reinstalling the system in this case.

**Comment by BienGudBoy** [comment]
> > Is it possible to upgrade from one version to newer btw? It kinda sucks to reinstall everything
> 
> It is recommended to keep the rule of keeping important data and software outside the system partition. There is not much to lose by reinstalling the system in this case.

I do have another partition, but things like Visual Studio won't work after reinstalling...
Anyways, I'm looking forward to your new build, my literally stock Windows build now refuses to install apps, no matter how much I tried to fix.
<img width="1205" alt="Screenshot 2023-05-22 at 09 40 34" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/c668f285-4706-4ade-b112-a7e656c334b1">

**Comment by WhatTheBlock** [comment]
![Snipaste_2023-05-22_10-53-13](https://github.com/WhatTheBlock/WindowsSimplify/assets/34786954/5456fe1d-beb4-4f25-a179-f411a87751d6)

uploading...

**Comment by WhatTheBlock** [comment]
> Visual Studio won't work after reinstalling

Visual Studio cannot be used because the Windows SDK and part of the Runtime will be installed in the system partition.

**Comment by falchion10** [comment]
I’ll test tomorrow, already 10pm for me. Thanks for updating the build :)

**Comment by BienGudBoy** [comment]
That's way faster than I expected. Downloading & testing now...

**Comment by BienGudBoy** [comment]
@WhatTheBlock 25371.1 build booted
Some quirks:
- ctfmon.exe crashes on first boot
<img width="752" alt="Screenshot 2023-05-22 at 11 07 39" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/8aaef565-1e0c-41ce-8c1d-945c473bc8b8">

- OOBE stuck in a black screen (can be fixed by logging out and in again)
- Edge survived (maybe because I'm a Safari/LibreWolf user...)
- 2GB RAM usage? Can it be considered a bug?
- Maybe more, I haven't fully tested it yet

Other than that, it seems to be working fine. Thank you :)
<img width="1952" alt="Screenshot 2023-05-22 at 11 11 00" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/2d6c8f8f-1cf6-4327-b98e-4f1adce49669">

**Comment by WhatTheBlock** [comment]
Thanks for your report. I will try to build a bugfix version. Could you please help me to test Store works or not?

**Comment by BienGudBoy** [comment]
> Thanks for your report. I will try to build a bugfix version. Could you please help me to test Store works or not?

Yes, Store works :) Can install and upgrade apps gracefully
<img width="1220" alt="Screenshot 2023-05-22 at 11 44 01" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/d6c28d26-c2f8-40d5-9aba-e9adeb24cb8c">

<img width="1215" alt="Screenshot 2023-05-22 at 11 44 32" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/3a19e6fd-9897-4def-b41c-185b7dfe486d">
<img width="1217" alt="Screenshot 2023-05-22 at 11 53 39" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/bb5729eb-4b43-4dbb-9474-edba521b8933">

**Comment by WhatTheBlock** [comment]
[Version 2 has been updated.](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.arm.230522)

**Comment by BienGudBoy** [comment]
@WhatTheBlock The same ctfmon.exe/OOBE thing happened, and now Edge is gone
Also one new bug: The network adapter gets automatically disabled after 60 seconds of booting with no way to turn it back on
<img width="778" alt="Screenshot 2023-05-22 at 19 15 26" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/96908843/50872476-d8e5-4151-aba5-830f06294c50">
With slightly less RAM used than last time, I guess blame Edge...

**Comment by WhatTheBlock** [comment]
> The network adapter gets automatically disabled after 60 seconds

Will the network be disconnected after 60 seconds?

**Comment by BienGudBoy** [comment]
> > The network adapter gets automatically disabled after 60 seconds
> 
> Will the network be disconnected after 60 seconds?

Yes, and I can't turn it back on until I do a reboot, and then 60 seconds later it gets disabled again...

**Comment by WhatTheBlock** [comment]
Ok, I'll try to fix this.

**Comment by falchion10** [comment]
Bugfix for the network adapter issue yet?

**Comment by WhatTheBlock** [comment]
Please wait, I plan to use the Mac mini I just bought to test.

**Comment by falchion10** [comment]
Good lord, I can't believe you actually bought a Mac mini just to test a Windows build.

**Comment by zhanker** [comment]
这个版本我也有尝试安装，但是我这里没有网络问题，我最后换了Parallels Desktop自带的win11，这个好像也是精简版本，但是稳定一点。

**Comment by WhatTheBlock** [comment]
**DEMO Video：** <br>
[![1](https://img.youtube.com/vi/FX8P7zbumbY/maxresdefault.jpg)](https://youtu.be/FX8P7zbumbY "DEMO Video")

25371.1 seems unstable, because the same configuration applied to 22631.1830 does not have so many problems.
[22631.1830_arm_230602](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/w11.arm.230602)

**Comment by falchion10** [comment]
*slow clap* Thank you so much for making this build! I'm very excited to try this out in a virtual machine!

**Comment by falchion10** [comment]
Build has been updated and finished. No known issues, everything seems to work perfectly as expected!
