### ISSUE TITLE
how do i disable the administrative privilages? 

### ISSUE THREAD

**Issue by sgrxrx** [WhatTheBlock/WindowsSimplify#76]
Everything opens by default in adminstrative privilage. How do i disable that? I am using latest Windows 11 pro(provided by you)? Please reply as soon as possible. Thanks.

**Comment by WhatTheBlock** [comment]
Some programs will be installed to `C:\Users\Administrator\AppData`. In this case, reinstallation is required.

**Comment by sgrxrx** [comment]
ohh okay thanks i guess
