### ISSUE TITLE
筆電安裝win10穩定版後，螢幕亮度無法調整

### ISSUE THREAD

**Issue by pigking0126** [WhatTheBlock/WindowsSimplify#77]
如題，在安裝win10穩定版後，筆電的調整亮度鍵沒有反應，
因為是和"f5"放在一起的按鍵(同時按"fn"和"f5"就能降低螢幕亮度)，
所以很容易就測試出"f5"的刷新頁面功能還是正常的，
其他功能也都正常。
之後用回原版系統沒有出現這個問題，
想請問應該要怎麼辦?

**Comment by WhatTheBlock** [comment]
筆電的官方驅動有裝嗎？我以前有遇過沒裝就沒辦法調

**Comment by pigking0126** [comment]
的確是這個問題!!感謝~~缺了intel顯示晶片的驅動~~裝了就好了!!
