### ISSUE TITLE
无法访问到网络

### ISSUE THREAD

**Issue by ifloppy** [WhatTheBlock/WindowsSimplify#78]
安装环境：VMware 17
![图片](https://github.com/WhatTheBlock/WindowsSimplify/assets/68799904/089dbbe1-e270-4c2a-9b05-ef179b768d59)

虚拟机网络配置：
![图片](https://github.com/WhatTheBlock/WindowsSimplify/assets/68799904/e6cb3030-5c65-41bb-8949-dd5ff1fb50c7)
虚拟机中完整安装了VMware Tool并进行了重启，问题仍未得到解决
重新创建虚拟机并安装，问题仍未得到解决
经测试，使用优启通的PE，在PE环境下能正常联网，排除VMware的问题
虚拟机的情况：
(似乎没有正确识别网卡)
![图片](https://github.com/WhatTheBlock/WindowsSimplify/assets/68799904/dbf914ef-31c6-4a66-9bfb-189f5defcadb)
![图片](https://github.com/WhatTheBlock/WindowsSimplify/assets/68799904/c6718eed-756b-4b7f-8075-8103e9cdd0dc)
尝试在设备管理器中指定使用VMware的网卡驱动，但问题仍然没有得到解决

**Comment by WhatTheBlock** [comment]
請使用3dp net安裝網卡驅動，如果我有提供demo使用影片應該會有這部分的展示，移除內建網卡驅動是為了盡可能減少不必要的空間佔用

**Comment by ifloppy** [comment]
> 

非常感谢，问题解决
