### ISSUE TITLE
Arm版本 win11 无法安装 Office

### ISSUE THREAD

**Issue by Anemone95** [WhatTheBlock/WindowsSimplify#79]
您好，我正在我的 parallel desktop 中安装精简版的 windows11， 但是当安装 office 时我遇到了问题：Error Code:30117-47(126)

**Comment by WhatTheBlock** [comment]
這個之前有人回報過，暫時還沒找到問題根源

**Comment by mio-19** [comment]
22631.1830嘛

**Comment by Kukmoon** [comment]
22631.2861 也不行
