### ISSUE TITLE
Windows 11 媒體播放器問題

### ISSUE THREAD

**Issue by Kevin0928000** [WhatTheBlock/WindowsSimplify#82]
您好，目前所使用的版本是 Windows 11 22623.1037 ，因為某些需求關係需要使用 windows media player 12 ，想問問看如何安裝回去??

**Comment by WhatTheBlock** [comment]
我比較好奇有什麼功能是media player有而第三方player沒有的?
如果只是個人習慣問題我建議不要使用精簡版系統
對於系統內建的功能有需求者都不該使用
