### ISSUE TITLE
請問您有試過可以安裝 Office 在 Win 11 ARM上嗎?

### ISSUE THREAD

**Issue by seabo1224** [WhatTheBlock/WindowsSimplify#87]
請問您有試過可以安裝 Office 在 Win 11 ARM上嗎?
我試了
Edition： Windows 11 Pro (ARM64)
OS Build： 22000.2124 Level 1

Edition： Windows 11 Pro (ARM64)
OS Build： 22631.1830
 都會報錯，無法安裝完成

測試環境
MacBook Air M1 with Parallels Desktop 18.0.3

**Comment by WhatTheBlock** [comment]
我還沒試過，未來有測試過的版本我會再特別標記一下

**Comment by seabo1224** [comment]
Edition： Windows 11 Pro (ARM64)
OS Build： 22621.900
同樣無法安裝 Office 報錯，無法安裝完成

**Comment by fwycxm** [comment]
我用msdn下的office(cn_office_professional_plus_2019_x86_x64_dvd)，安装成功。
22631.1830_arm_230602
虚拟机pd18
