### ISSUE TITLE
Vmware Tools 安装完毕后没有效果。

### ISSUE THREAD

**Issue by TryA9ain** [WhatTheBlock/WindowsSimplify#88]
VMware-Fusion 13 pro，安装 windows 11 arm lv2 版本，Vmware Tools 成功安装后，没有效果。
ISO下载地址:https://github.com/WhatTheBlock/WindowsSimplify/releases/download/iso/22000.2124_arm_230712_lv2.iso

<img width="555" alt="image" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/51145610/fd5b7fde-dfaf-403c-8eb7-b2c96dfa01d8">

并且在卸载程序的地方也并未显示 vm tool。

<img width="787" alt="image" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/51145610/1364ba5b-a244-42a7-beb0-a2b6fd540612">

**Comment by WhatTheBlock** [comment]
VMware本身未完整支援Win11 ARM，因此不會有像x86那樣功能完整的驅動，只要powershell顯示無錯誤就是安裝完成
