### ISSUE TITLE
Cannot boot with Win11 25926.1000_atlas_230813_lv2.iso

### ISSUE THREAD

**Issue by rwlin** [WhatTheBlock/WindowsSimplify#91]
Cannot boot with Win11 25926.1000_atlas_230813_lv2.iso
Please check it.

**Comment by WhatTheBlock** [comment]
Please ensure that the BIOS boot mode is pure UEFI, and compatibility mode cannot be used.

**Comment by rwlin** [comment]
Thanks. My problem is that the disk size too small (at least 64GB)
