### ISSUE TITLE
Win10 ARM64 简体中文版21390.1 

### ISSUE THREAD

**Issue by lesong** [WhatTheBlock/WindowsSimplify#92]
你好大神，我正在使用你的win10 ARM64英文版，感觉很强大,占用资源少，非常稳定流畅
感谢大神的辛苦付出，让我用到最合心意的系统
但是我的英文不是很好，并且有的中文软件显示乱码，
有幸在网上找到了同版本的中文镜像（21390.1 ），你可以做一个中文版本的吗，
保留Microsoft store，中文输入法相关和windows update

这是我上传的中文镜像：https://archive.org/details/21390.1-professional-arm-64-zh-cn

**Comment by WhatTheBlock** [comment]
感謝提供中文版，但成品不能保證各項功能能如期運作，
因為21390.1必須移除時間炸彈，這個方法會導致office無法啟用等副作用

**Comment by lesong** [comment]
> 感谢提供中文版，但最终不能保证各项功能能如期兼容， 因为21390.1必须移除时间炸弹，此方法会导致office无法启用等后果



> 感谢提供中文版，但最终不能保证各项功能能如期兼容， 因为21390.1必须移除时间炸弹，此方法会导致office无法启用等后果

没关系，因为是虚拟机使用，office我使用mac版，你做的在PD19上很稳定，占用资源很少，用起来很顺心，期待大神的中文版本发布

**Comment by qiu96988** [comment]
> 你好大神，我正在使用你的win10 ARM64英文版，感觉很强大,占用资源少，非常稳定流畅 感谢大神的辛苦付出，让我用到最合心意的系统 但是我的英文不是很好，并且有的中文软件显示乱码， 有幸在网上找到了同版本的中文镜像（21390.1 ），你可以做一个中文版本的吗， 保留Microsoft store，中文输入法相关和windows update
> 
> 这是我上传的中文镜像：https://archive.org/details/21390.1-professional-arm-64-zh-cn

请问能否给我一个百度网盘或者其他下载链接呢？这个网站下载镜像好慢（）

**Comment by ryanwuson** [comment]
<img width="422" alt="iShot_2024-01-26_14 06 54" src="https://github.com/WhatTheBlock/WindowsSimplify/assets/20364388/7449d9a5-f01a-4bde-8054-791af73b7f34">

您好，我使用的是parallels desktop 19來安裝，安裝 parallels tools出現如上圖錯誤，按下確定後，即可繼續安裝，不知道對系統有沒有影響，謝謝
