### ISSUE TITLE
help me plz 🙏

### ISSUE THREAD

**Issue by maxfaa** [WhatTheBlock/WindowsSimplify#95]
For my OS course (I'm a student) I need a Windows 10 Enterprise iso. The issue is, I need a **ARM64** version... I search everywhere on the Internet and didn't find it.
I know it's not the right place but I'm just looking for people able to help me with this... :(

**Comment by BienGudBoy** [comment]
Just get a Pro ISO, install it, and then install an Enterprise key.

**Comment by maxfaa** [comment]
> Just get a Pro ISO, install it, and then install an Enterprise key.

Ok but where can I get a Windows 10 (Pro) ARM64 ISO?

**Comment by WhatTheBlock** [comment]
What build version do you need? (16299 ~ 19045)

Which system language?

**Comment by maxfaa** [comment]
> What build version do you need? (16299 ~ 19045)

The latest one

> Which system language?

French

**Comment by WhatTheBlock** [comment]
> > What build version do you need? (16299 ~ 19045)
> 
> The latest one
> 
> > Which system language?
> 
> French
> (belgian french would be even better)

[19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/utils/19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip)

**Comment by maxfaa** [comment]
> > > What build version do you need? (16299 ~ 19045)
> > 
> > 
> > The latest one
> > > Which system language?
> > 
> > 
> > French
> > (belgian french would be even better)
> 
> [19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/utils/19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip)
> 
> unzip and run `uup_download_windows.cmd` you will get a win10 enterprise edition iso.

Thanks a lot!! (I'm on Mac but luckily I own a Windows PC too so I'll be able to execute the .cmd file)
Otherwise, can I know how you got this ISO?

**Comment by maxfaa** [comment]
> > > What build version do you need? (16299 ~ 19045)
> > 
> > 
> > The latest one
> > > Which system language?
> > 
> > 
> > French
> > (belgian french would be even better)
> 
> [19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/utils/19045.3516_arm64_fr-fr_professional_28907042_convert_virtual.zip)
> 
> unzip and run `uup_download_windows.cmd` you will get a win10 enterprise edition iso.

It doesn't work with VMWare :/
![image](https://github.com/WhatTheBlock/WindowsSimplify/assets/71935156/691d3041-1552-494b-b69b-5b6872bebfb3)

**Comment by maxfaa** [comment]
@WhatTheBlock however your ISO from https://github.com/WhatTheBlock/WindowsSimplify/blob/master/10/arm64.md#-windows-10-arm64 does work! Unfortunatly I need a full version of Windows while the working one lacks a lot of features.

**Comment by WhatTheBlock** [comment]
If you want to run on a virtual machine, Win10 ARM only supports build 21390.

**Comment by maxfaa** [comment]
> If you want to run on a virtual machine, Win10 ARM only supports build 21390.

Oh ok and where can I download it?

**Comment by WhatTheBlock** [comment]
[link](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/base)

**Comment by maxfaa** [comment]
> [link](https://github.com/WhatTheBlock/WindowsSimplify/releases/tag/base)

Thanks ^^
btw which version is it (Pro, Enterprise,...)?

**Comment by WhatTheBlock** [comment]
win10 pro

**Comment by maxfaa** [comment]
it's working thank you soooo much guys

**Comment by maxfaa** [comment]
@WhatTheBlock some features don't work :/ (like device manager)
![image](https://github.com/WhatTheBlock/WindowsSimplify/assets/71935156/810e29e5-31f1-4dfa-9049-63f4791d6095)

**Comment by maxfaa** [comment]
issue fixed :)

**Comment by maxfaa** [comment]
Hi, I'm back 😅
I need a Windows Server ARM64 iso (10 or 11) again for my network course...

**Comment by WhatTheBlock** [comment]
Windows Server does not provide ARM64 builds.

**Comment by maxfaa** [comment]
> Windows Server does not provide ARM64 builds.

Bruh 
There really is no way to get one??? 😭

**Comment by WhatTheBlock** [comment]
The build platform depends on Microsoft, so there is currently no ARM64 version.

**Comment by maxfaa** [comment]
https://betawiki.net/wiki/Windows_Server_build_14901

**Comment by WhatTheBlock** [comment]
There has never been an official release of an ARM64 build for Windows Server.  Compatibility will also not be officially supported.  So pursuing an ARM64 build at this stage is pointless. If you insist on testing then I'm sorry I can't help.

**Comment by maxfaa** [comment]
> There has never been an official release of an ARM64 build for Windows Server. Compatibility will also not be officially supported. So pursuing an ARM64 build at this stage is pointless. If you insist on testing then I'm sorry I can't help.

Oooh, sad :/
Thanks anyway
