### ISSUE TITLE
win11 arm64版本怎麼恢復應用商店呢？

### ISSUE THREAD

**Issue by kero990** [WhatTheBlock/WindowsSimplify#96]
我在虛擬機上安裝了win11 arm64 lv1，但我發現該版本內既沒有edge，也沒有應用商店。這導致該系統實際上無法靠本機打開任何網頁，請問有什麼辦法安裝edge或恢復商店嗎？我不確定首頁的商店恢復包是否適用於arm64版本

另外，該版本似乎會丟失語言包，重啓後有一定概率回到English版本並無法切換會安裝的語言包。

**Comment by WhatTheBlock** [comment]
[已回覆](https://github.com/WhatTheBlock/WindowsSimplify/issues/60#issuecomment-1756641877)

**Comment by byteat** [comment]
> 我在虛擬機上安裝了win11 arm64 lv1，但我發現該版本內既沒有edge，也沒有應用商店。這導致該系統實際上無法靠本機打開任何網頁，請問有什麼辦法安裝edge或恢復商店嗎？我不確定首頁的商店恢復包是否適用於arm64版本
> 
> 另外，該版本似乎會丟失語言包，重啓後有一定概率回到English版本並無法切換會安裝的語言包。

确实会丢失语言包，但重启后有一定的概率会恢复，不知道什么原因。。
