### ISSUE TITLE
請問有沒有提供W7 Pro (EN) X64  以注入USB3.0&Nvme驅動的版本??

### ISSUE THREAD

**Issue by ytalai** [WhatTheBlock/WindowsSimplify#99]

**Comment by ytalai** [comment]
我有嘗試下載
[發佈日期：2021/04/23](https://github.com/WhatTheBlock/WindowsSimplify/blob/master/7/README.md#release-date20210423-1)
版本： Windows 7 專業版 (x64)

作業系統版本： 7601.17514

ISO大小： 1.61GB

下載： [連結](http://tiny.cc/w7_en_20210423_f_o)

SHA-256： EAEC5EC4748A10B0E5F88816BE6E256E752D1557D22BBB092EB0963FB28BF70E

注意：

如果您想安裝累積更新，請下載[此檔案。](https://github.com/WhatTheBlock/WindowsSimplify/releases/download/v2021.04.23/7601.17514_to_7601.24576.exe)（7601.17514 至 7601.24576）

這版本來使用工具注入
但不論是技嘉華碩或是聯想的工具都無法注入

**Comment by WhatTheBlock** [comment]
試試win7頁面裡最新發布的lv1版本

**Comment by ytalai** [comment]
請問我可以付費請您協助我客製精簡版的W7ProX64 以及 精簡版的LTSB2019嗎???
若您有意願,麻煩來信ytalai@gmail.com
我會將我的需求提供給您
您在依照我的需求報價~
感謝

**Comment by WhatTheBlock** [comment]
> 請問我可以付費請您協助我客製精簡版的W7ProX64 以及 精簡版的LTSB2019嗎???
> 若您有意願,麻煩來信ytalai@gmail.com
> 我會將我的需求提供給您
> 您在依照我的需求報價~
> 感謝

已發信，再麻煩提供需求給我參考，謝謝
